spring:
  application:
    name: computer_helper

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/computer_helper
    username: postgres
    password: password

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

bot:
  token: ${BOT_TOKEN:7314339886:AAGekycYZXqCLSqQse-xJL8bCFDUqkE_Cfw}