CREATE TABLE IF NOT EXISTS clients (
   id BIGSERIAL PRIMARY KEY,
   chat_id BIGINT UNIQUE NOT NULL,
   full_name VARCHAR(100) NOT NULL,
   phone VARCHAR(50) NOT NULL,
   email VARCHAR(100) NOT NULL,
   address VARCHAR(500) NOT NULl
)